name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ['3.8'] #, '3.10']
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U jupyterlab~=3.1 check-manifest

    - name: Lint the extension
      run: |
        set -eux
        jlpm
        jlpm run lint:check
    
    - name: Test the extension
      run: |
        set -eux
        jlpm run test

    - name: Build the extension
      run: |
        set -eux
        python -m pip install .[test]

        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "getsshpubkey.*OK"

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "getsshpubkey.*OK"
        python -m jupyterlab.browser_check

    - name: Package the extension
      run: |
        set -eux
        check-manifest -v

        pip install build
        python -m build
        pip uninstall -y "getsshpubkey" jupyterlab